module Mammoth
  # Adapter object used by CDC::Concurrent::ProcessorPool.
  class DeliveryProcessor
    @delivery_worker: untyped
    @delivery_unit: untyped

    attr_reader delivery_worker: untyped
    attr_reader delivery_unit: untyped

    def self.concurrent_safe!: () -> bool
    def self.concurrent_safe?: () -> bool
    def self.concurrent_safe: () -> bool

    def concurrent_safe?: () -> bool
    def concurrent_safe: () -> bool

    def initialize: (delivery_worker: untyped, ?delivery_unit: untyped) -> void

    def call: (untyped work) -> untyped
    def process: (untyped work) -> untyped
  end
end
